# Generated by Django 6.1.1 on 2026-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/')),
                ('type', models.CharField(choices=[('school', 'School'), ('university', 'University'), ('college', 'College'), ('training_center', 'Training Center'), ('company', 'Company'), ('ngo', 'NGO'), ('community', 'Community Organization'), ('innovation_hub', 'Innovation Hub')], max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('partnership_info', models.TextField(blank=True, help_text='Details about the nature of the partnership')),
                ('is_active_partner', models.BooleanField(default=True)),
                ('programs_conducted', models.ManyToManyField(blank=True, related_name='institutions', to='programs.program')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
