# Generated by Django 6.1.1 on 2026-09-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('featured_image', models.ImageField(upload_to='projects/featured/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('robotics', 'Robotics'), ('ai', 'Artificial Intelligence'), ('iot', 'Internet of Things'), ('electronics', 'Electronics'), ('automation', 'Automation'), ('school_innovation', 'School Innovation')], max_length=30)),
                ('target_audience', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('university', 'University / College'), ('professional', 'Professional / Organizations')], max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube link')),
                ('project_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='technologies.technology')),
            ],
            options={
                'ordering': ['-project_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
