# Generated by Django 6.1.1 on 2026-09-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('position', models.CharField(help_text='e.g. Founder / Director, Robotics Engineer', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('short_bio', models.CharField(max_length=300)),
                ('full_bio', models.TextField()),
                ('areas_of_expertise', models.TextField(help_text='One area per line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('website', 'Website')], max_length=20)),
                ('url', models.URLField()),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='team.teammember')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
