# Generated by Django 6.1.1 on 2026-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class, e.g. "fa-solid fa-robot"', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('description', models.TextField()),
                ('target_clients', models.TextField(help_text='One client type per line, e.g. Schools, Companies, NGOs')),
                ('benefits', models.TextField(help_text='One benefit per line')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
