# Generated by Django 6.1.1 on 2026-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video (YouTube)')], max_length=10)),
                ('category', models.CharField(choices=[('robotics', 'Robotics'), ('arduino', 'Arduino'), ('programming', 'Programming'), ('ai', 'Artificial Intelligence'), ('electronics', 'Electronics'), ('projects', 'Projects'), ('training', 'Training'), ('events', 'Events')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube URL — required if media type is Video')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
